---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stackgres-operator
  namespace: stackgres
spec:
  releaseName: stackgres-operator
  interval: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: stackgres-operator
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: stackgres
        namespace: flux-system

  # https://gitlab.com/ongresinc/stackgres/-/blob/main/stackgres-k8s/install/helm/stackgres-operator/values.yaml
  values:
    deploy:
      restapi: false
    prometheus:
      allowAutobind: true
    grafana:
      autoEmbed: false

  dependsOn:
    - name: kube-prometheus-stack
      namespace: o11y
