# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: o11y
spec:
  releaseName: kube-prometheus-stack
  interval: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  values:
    nameOverride: prometheus
    grafana:
      enabled: false
