---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-operator
  namespace: o11y
spec:
  releaseName: otel-operator
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    admissionWebhooks:
      certManager:
        enabled: true

  dependsOn:
    - name: cert-manager
      namespace: cert-manager
