---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/metrics-server
  - ../../base/o11y
  - ../../base/cert-manager
  - ../../base/dragonfly
  - ../../base/decidim

patches:
  - path: ./patches/metrics-server.release.yml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: metrics-server
      namespace: kube-system

  - path: ./patches/dragonfly.release.yml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: dragonfly
      namespace: dragonfly-system

  - path: ./patches/kube-prometheus-stack.release.yml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: o11y

  - path: ./patches/cert-manager.release.yml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
