---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/metrics-server
  - ../../base/o11y
  - ../../base/dragonfly

patches:
  - path: ./patches/metrics-server.release.yml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: metrics-server
      namespace: kube-system

  - path: ./patches/dragonfly.release.yml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: dragonfly
      namespace: dragonfly-system
