---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dragonfly
spec:
  interval: 30m
  url: https://dragonflyoss.github.io/helm-charts/
  # type: oci
  # url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
