---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly-system
spec:
  releaseName: dragonfly
  interval: 5m
  chart:
    spec:
      chart: dragonfly
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  install:
    remediation:
      retries: 3

  # https://github.com/dragonflydb/dragonfly/blob/main/contrib/charts/dragonfly/values.yaml
  values:
    podSecurityContext:
      fsGroup: 2000

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    storage:
      enabled: true
      requests: 128Mi

    extraArgs:
      - --dbfilename=dump.rdb
      - --snapshot_cron=0 * * * *
